package org.homio.addon.firmata.model;

import org.homio.api.model.Icon;

/**
 * Generated by AI from Firmata Board.h file
 */
public class PinoutModel {
  private static String getPinLabelInternal(String boardName, int pinIndex) {
    boardName = boardName.toLowerCase(); // For case-insensitive matching

    return switch (boardName) {
      case "uno", "__avr_atmega168__", "__avr_atmega328p__", "__avr_atmega328__" -> getUnoPinLabel(pinIndex);
      case "avr_nano_every", "arduino_nano_every", "arduino_avr_nano_every" -> getNanoEveryPinLabel(pinIndex);
      case "mega", "__avr_atmega1280__", "__avr_atmega2560__" -> getMegaPinLabel(pinIndex);
      case "due", "__sam3x8e__" -> getDuePinLabel(pinIndex);
      case "mkr1000", "arduino_samd_mkr1000" -> getMKR1000PinLabel(pinIndex);
      case "mkrzero", "arduino_samd_mkrzero" -> getMKRZeroPinLabel(pinIndex);
      case "mkrfox1200", "arduino_samd_mkrfox1200" -> getMKRFox1200PinLabel(pinIndex);
      case "mkrwan1300", "arduino_samd_mkrwan1300" -> getMKRWAN1300PinLabel(pinIndex);
      case "mkrgsm1400", "arduino_samd_mkrgsm1400" -> getMKRGSM1400PinLabel(pinIndex);
      case "zero", "_variant_arduino_zero_" -> getZeroPinLabel(pinIndex);
      case "primo", "arduino_primo" -> getPrimoPinLabel(pinIndex);
      case "101", "_variant_arduino_101_x_" -> get101PinLabel(pinIndex);
      case "teensy1.0", "__avr_at90usb162__" ->
        getTeensy1_0PinLabel(pinIndex); // Leonardo and Teensy 2.0 share the same chip, but different pinouts might need separate handling if needed for other Firmata features
      case "teensy2.0", "__avr_atmega32u4__",
           "core_teensy" -> // Added explicitly for clarity if you want to differentiate Teensy 2.0 more precisely
        getTeensy2_0PinLabel(pinIndex);
      case "teensy3.5", "teensy3.6", "__mk64fx512__", "__mk66fx1m0__" -> getTeensy3_5_3_6PinLabel(pinIndex);
      case "teensy3.0", "teensy3.1", "teensy3.2", "__mk20dx128__", "__mk20dx256__" ->
        getTeensy3_0_3_1_3_2PinLabel(pinIndex);
      case "teensylc", "__mkl26z64__" -> getTeensyLCPinLabel(pinIndex);
      case "teensy++1.0", "teensy++2.0", "__avr_at90usb646__", "__avr_at90usb1286__" ->
        getTeensyPlusPlusPinLabel(pinIndex);
      case "leonardo" -> getLeonardoPinLabel(pinIndex);
      case "galileo", "edison", "arduino_linux" -> getGalileoEdisonPinLabel(pinIndex);
      case "blenano", "ble_nano" -> getBLENanoPinLabel(pinIndex);
      case "pinoccio", "arduino_pinoccio" -> getPinoccioScoutPinLabel(pinIndex);
      case "sanguino", "__avr_atmega644p__", "__avr_atmega644__" -> getSanguinoPinLabel(pinIndex);
      case "illuminato", "__avr_atmega645__" -> getIlluminatoPinLabel(pinIndex);
      case "esp8266" -> getESP8266PinLabel(pinIndex);
      case "stm32", "arduino_arch_stm32" -> getSTM32PinLabel(pinIndex);
      case "esp32" -> getESP32PinLabel(pinIndex);
      case "adafruit_nrf52", "arduino_nrf52_adafruit" -> getAdafruitNRF52PinLabel(pinIndex);
      case "raspberrypipico", "target_rp2040", "target_raspberry_pi_pico" -> getRaspberryPiPicoPinLabel(pinIndex);
      case "unor4minima", "arduino_unor4_minima", "unor4wifi", "arduino_unor4_wifi" -> getUnoR4PinLabel(pinIndex);
      default -> null;
    };
  }

  // --- Pin Label Generation Methods for Each Board ---

  private static String getUnoPinLabel(int pinIndex) {
    if (pinIndex >= 2 && pinIndex <= 13) {
      return "D" + pinIndex; // Digital pins D2–D13
    } else if (pinIndex >= 14 && pinIndex <= 19) {
      return "A" + (pinIndex - 14); // Analog pins A0–A5
    }
    return null;
  }

  private static String getNanoEveryPinLabel(int pinIndex) {
    if (pinIndex >= 14 && pinIndex <= 21) {
      return "A" + (pinIndex - 14); // Analog pins A0-A7
    } else if (pinIndex >= 2 && pinIndex <= 13) { // Digital pins 2-13 (Explicitly exclude analog range)
      return "D" + (pinIndex);
    } else if (pinIndex == 22) {
      return "SDA"; // I2C SDA
    } else if (pinIndex == 23) {
      return "SCL"; // I2C SCL
    }
    return null;
  }

  private static String getMegaPinLabel(int pinIndex) {
    if (pinIndex >= 2 && pinIndex <= 53) {
      return "D" + pinIndex; // Digital pins D2-D53
    } else if (pinIndex >= 54 && pinIndex <= 69) {
      return "A" + (pinIndex - 54); // Analog pins A0-A15
    }
    return null;
  }

  private static String getDuePinLabel(int pinIndex) {
    if (pinIndex >= 54 && pinIndex <= 65) { // FIRMATA_IS_PIN_ANALOG range
      return "A" + (pinIndex - 54); // Analog pins A0-A11
    } else if (pinIndex >= 2 && pinIndex <= 65) { // TOTAL_DEFAULT_PINS -1 because we start from 2
      return "D" + (pinIndex); // Digital pins 2-65 (Default Digital + Analog Range in Boards.h)
    } else if (pinIndex == 70) {
      return "SDA"; // I2C SDA
    } else if (pinIndex == 71) {
      return "SCL"; // I2C SCL
    }
    return null;
  }

  private static String getMKR1000PinLabel(int pinIndex) {
    if (pinIndex == 11) {
      return "SDA"; // I2C SDA
    } else if (pinIndex == 12) {
      return "SCL"; // I2C SCL
    } else if (pinIndex == 13) {
      return "Serial RX"; // Serial RX
    } else if (pinIndex == 14) {
      return "Serial TX"; // Serial TX
    } else if (pinIndex >= 15 && pinIndex <= 21) {
      return "A" + (pinIndex - 15); // Analog pins A0-A6
    } else if (pinIndex >= 0 && pinIndex <= 21) { // Digital pins 0-21 excluding Serial RX/TX (13,14)
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getMKRZeroPinLabel(int pinIndex) {
    if (pinIndex == 11) {
      return "SDA";
    } else if (pinIndex == 12) {
      return "SCL";
    } else if (pinIndex == 13) {
      return "Serial RX";
    } else if (pinIndex == 14) {
      return "Serial TX";
    } else if (((pinIndex >= 15 && pinIndex <= 21) || pinIndex == 33)) {
      return "A" + (pinIndex - 15);
    } else if (pinIndex >= 0 && pinIndex <= 21 || pinIndex == 32) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getMKRFox1200PinLabel(int pinIndex) {
    if (pinIndex == 11) {
      return "SDA";
    } else if (pinIndex == 12) {
      return "SCL";
    } else if (pinIndex == 13) {
      return "Serial RX";
    } else if (pinIndex == 14) {
      return "Serial TX";
    } else if (((pinIndex >= 15 && pinIndex <= 21) || pinIndex == 32)) {
      return "A" + (pinIndex - 15);
    } else if (((pinIndex >= 0 && pinIndex <= 21))) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getMKRWAN1300PinLabel(int pinIndex) {
    if (pinIndex == 11) {
      return "SDA";
    } else if (pinIndex == 12) {
      return "SCL";
    } else if (pinIndex == 13) {
      return "Serial RX";
    } else if (pinIndex == 14) {
      return "Serial TX";
    }
    if (((pinIndex >= 15 && pinIndex <= 21) || pinIndex == 32)) {
      return "A" + (pinIndex - 15);
    } else if (((pinIndex >= 0 && pinIndex <= 21))) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getMKRGSM1400PinLabel(int pinIndex) {
    if (pinIndex == 11) {
      return "SDA";
    } else if (pinIndex == 12) {
      return "SCL";
    } else if (pinIndex == 13) {
      return "Serial RX";
    } else if (pinIndex == 14) {
      return "Serial TX";
    } else if (((pinIndex >= 15 && pinIndex <= 21) || pinIndex == 32)) {
      return "A" + (pinIndex - 15);
    } else if (((pinIndex >= 0 && pinIndex <= 21))) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getZeroPinLabel(int pinIndex) {
    if (pinIndex == 20) {
      return "SDA"; // SDA pin
    } else if (pinIndex == 21) {
      return "SCL"; // SCL pin
    } else if (pinIndex >= 14 && pinIndex <= 19) {
      return "A" + (pinIndex - 14); // Analog pins A0-A5
    } else if (pinIndex >= 0 && pinIndex <= 13) {
      return "D" + pinIndex; // Digital pins D0-D13
    }
    return null;
  }

  private static String getPrimoPinLabel(int pinIndex) {
    if (pinIndex == 20) {
      return "SDA";
    } else if (pinIndex == 21) {
      return "SCL";
    } else if (pinIndex >= 14 && pinIndex < 20) {
      return "A" + (pinIndex - 14);
    } else if (pinIndex >= 2 && pinIndex < 20) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String get101PinLabel(int pinIndex) {
    if (pinIndex == 18) {
      return "SDA";
    } else if (pinIndex == 19) {
      return "SCL";
    } else if (pinIndex >= 14 && pinIndex < 14 + 6) { // TOTAL_ANALOG_PINS is NUM_ANALOG_INPUTS which is 6 for 101
      return "A" + (pinIndex - 14);
    } else if (pinIndex >= 0 && pinIndex <= 20) {
      return "D" + (pinIndex);
    } else
      return null;
  }

  private static String getTeensy1_0PinLabel(int pinIndex) {
    if (pinIndex >= 0 && pinIndex < 21) {
      return "D" + (pinIndex);
    }
    return null; // No analog pins on Teensy 1.0
  }

  private static String getTeensy2_0PinLabel(int pinIndex) {
    if (pinIndex >= 0 && pinIndex < 11) {
      return "D" + (pinIndex);
    } else if (pinIndex >= 11 && pinIndex <= 22) {
      return "A" + (pinIndex - 11); // A0-A11
    }
    return null;
  }

  private static String getTeensy3_5_3_6PinLabel(int pinIndex) {
    if (pinIndex == 18) {
      return "SDA";
    } else if (pinIndex == 19) {
      return "SCL";
    } else if (((pinIndex >= 14 && pinIndex <= 23) || (pinIndex >= 31 && pinIndex <= 39) || (pinIndex >= 49 && pinIndex <= 50) || (pinIndex >= 64 && pinIndex <= 69))) {
      // More complex analog mapping, refer to Boards.h for details if needed to refine analog labels further.
      return "A" + getTeensyAnalogIndex(pinIndex);
    } else if (pinIndex >= 0 && pinIndex <= 63) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static int getTeensyAnalogIndex(int pinIndex) {
    if (pinIndex >= 14 && pinIndex <= 23) return pinIndex - 14;
    if (pinIndex >= 31 && pinIndex <= 39) return pinIndex - 19;
    if (pinIndex >= 49 && pinIndex <= 50) return pinIndex - 26;
    if (pinIndex >= 64 && pinIndex <= 69) return pinIndex - 55;
    if (pinIndex <= 67) return pinIndex - 45; // Corrected from example based on Boards.h, might need verification
    return pinIndex - 43; // Corrected from example based on Boards.h, might need verification
  }


  private static String getTeensy3_0_3_1_3_2PinLabel(int pinIndex) {
    if (pinIndex == 18) {
      return "SDA";
    } else if (pinIndex == 19) {
      return "SCL";
    } else if (((pinIndex >= 14 && pinIndex <= 23) || (pinIndex >= 34 && pinIndex <= 38))) {
      return "A" + getTeensy3_0_3_1_3_2AnalogIndex(pinIndex);
    } else if (pinIndex >= 0 && pinIndex <= 33) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static int getTeensy3_0_3_1_3_2AnalogIndex(int pinIndex) {
    if (pinIndex >= 14 && pinIndex <= 23) return pinIndex - 14;
    return pinIndex - 24;
  }


  private static String getTeensyLCPinLabel(int pinIndex) {
    if (pinIndex == 18) {
      return "SDA";
    } else if (pinIndex == 19) {
      return "SCL";
    } else if (pinIndex >= 14 && pinIndex <= 26) { // All remaining are analog
      return "A" + (pinIndex - 14);
    } else if (pinIndex >= 0 && pinIndex <= 26) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getTeensyPlusPlusPinLabel(int pinIndex) {
    if (pinIndex == 0) {
      return "SDA";
    } else if (pinIndex == 1) {
      return "SCL";
    } else if (pinIndex >= 38 && pinIndex < 46) { //Analog range in Boards.h is >= 38 and < TOTAL_PINS(46)
      return "A" + (pinIndex - 38);
    } else if (pinIndex >= 0 && pinIndex < 46) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getLeonardoPinLabel(int pinIndex) {
    if (pinIndex == 2) {
      return "SDA";
    } else if (pinIndex == 3) {
      return "SCL";
    } else if (pinIndex >= 18 && pinIndex < 30) { // Analog Range (18-29)
      return "A" + (pinIndex - 18);
    } else if (pinIndex >= 0 && pinIndex < 18) { // Digital + SPI Range (0-17)
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getGalileoEdisonPinLabel(int pinIndex) {
    if (pinIndex == 18) {
      return "SDA";
    } else if (pinIndex == 19) {
      return "SCL";
    } else if (pinIndex >= 2 && pinIndex <= 13) {
      return "D" + (pinIndex);
    } else if (pinIndex >= 14 && pinIndex <= 19) {
      return "A" + (pinIndex - 14);
    }
    return null;
  }

  private static String getBLENanoPinLabel(int pinIndex) {
    if (pinIndex >= 2 && pinIndex <= 7) {
      return "D" + (pinIndex); // Digital pins 2-7
    } else if (pinIndex >= 8 && pinIndex <= 12) {
      return "A" + (pinIndex - 8); // Analog pins A0-A4 (A0-A5 in comment but only 3 analog defined)
    } else if (pinIndex == 14) {
      return "A5"; // Analog pin A5
    }
    return null;
  }

  private static String getPinoccioScoutPinLabel(int pinIndex) {
    if (pinIndex == 15) {
      return "SCL";
    } else if (pinIndex == 16) {
      return "SDA";
    } else if (pinIndex == 13) {
      return "Serial RX";
    } else if (pinIndex == 14) {
      return "Serial TX";
    } else if (pinIndex >= 24 && pinIndex <= 31) {
      return "A" + (pinIndex - 24);
    } else if (pinIndex >= 2 && pinIndex <= 16) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getSanguinoPinLabel(int pinIndex) {
    if (pinIndex == 16) {
      return "SDA";
    } else if (pinIndex == 17) {
      return "SCL";
    } else if (pinIndex >= 2 && pinIndex <= 23) {
      return "D" + (pinIndex);
    } else if (pinIndex >= 24 && pinIndex <= 31) {
      return "A" + (pinIndex - 24);
    }
    return null;
  }

  private static String getIlluminatoPinLabel(int pinIndex) {
    if (pinIndex == 4) {
      return "SDA";
    } else if (pinIndex == 5) {
      return "SCL";
    } else if (pinIndex >= 2 && pinIndex <= 35) {
      return "D" + (pinIndex);
    } else if (pinIndex >= 36 && pinIndex <= 41) {
      return "A" + (pinIndex - 36);
    }
    return null;
  }

  private static String getESP8266PinLabel(int pinIndex) {
    return switch (pinIndex) {
      case 5 -> "D1 (SCL)";
      case 4 -> "D2 (SDA)";
      case 0 -> "D3";
      case 2 -> "D4";
      case 14 -> "D5";
      case 12 -> "D6";
      case 13 -> "D7";
      case 15 -> "D8";
      case 16 -> "D0";
      case 3 -> "RX";
      case 1 -> "TX";
      case 17 -> "A0"; // Analog pin (if using some libraries)
      default -> null;
    };
  }

  private static String getSTM32PinLabel(int pinIndex) {
    // STM32 pin labeling is very board-specific. This is a very basic example.
    // You'll likely need to refine this based on the specific STM32 board variant you are using.
    if (pinIndex >= 0 && pinIndex < 100) { // Assuming a maximum of 100 digital pins for STM32 (adjust as needed)
      return "GPIO" + pinIndex; // Generic GPIO label. STM32 often uses GPIO naming.
    } else if (pinIndex >= 100 && pinIndex < 100 + 16) { // Assuming up to 16 analog pins starting from A0 (adjust as needed)
      return "A" + (pinIndex - 100);
    }
    return null;
  }

  private static String getESP32PinLabel(int pinIndex) {
    // ESP32 pin labeling can also be a bit board-specific. This is a general approach.
    if (pinIndex == 21) {
      return "SDA";
    } else if (pinIndex == 22) {
      return "SCL";
    } else if (((pinIndex == 0) || (pinIndex == 2) || (pinIndex == 4) || ((pinIndex) >= 12 && (pinIndex) < 16) || ((pinIndex >= 25 && pinIndex < 28) || ((pinIndex) >= 32 && (pinIndex) < 37) || (pinIndex) == 39))) {
      return "A" + digitalPinToAnalogChannelESP32(pinIndex); // Using a helper function for ESP32 Analog Channel mapping
    } else if (pinIndex == 5 || pinIndex >= 12 && pinIndex < 24 || pinIndex >= 32 && pinIndex <= 39) {
      return "D" + pinIndex; // Or "D" + pinIndex if you prefer digital style
    }
    return null;
  }

  // Helper function to get ESP32 Analog Channel (mimicking digitalPinToAnalogChannel in ESP32 core)
  private static int digitalPinToAnalogChannelESP32(int pinIndex) {
    // This is a simplified mapping. Refer to ESP32 documentation for precise mapping if needed.
    if (pinIndex == 0) return 1; // A1
    if (pinIndex == 2) return 2; // A2
    if (pinIndex == 4) return 3; // A3
    if (pinIndex >= 12 && pinIndex < 16) return pinIndex - 12 + 4; // A4-A7
    if (pinIndex >= 25 && pinIndex < 28) return pinIndex - 25 + 8; // A8-A10
    if (pinIndex >= 32 && pinIndex < 37) return pinIndex - 32 + 11; // A11-A15
    if (pinIndex == 39) return 16; // A16
    return -1; // Not an analog pin (or mapping not defined)
  }


  private static String getAdafruitNRF52PinLabel(int pinIndex) {
    if (pinIndex == 28) return "A0"; // PIN_A0 = 28
    else if (pinIndex == 29) return "A1"; // PIN_A1 = 29
    else if (pinIndex == 30) return "A2"; // PIN_A2 = 30
    else if (pinIndex == 31) return "A3"; // PIN_A3 = 31
    else if (pinIndex == 2) return "A4";  // PIN_A4 = 2
    else if (pinIndex == 3) return "A5";  // PIN_A5 = 3
    else if (pinIndex == 4) return "A6";  // PIN_A6 = 4
    else if (pinIndex == 5) return "A7";  // PIN_A7 = 5
    else if (pinIndex == 6) return "SDA"; // PIN_WIRE_SDA = 6
    else if (pinIndex == 7) return "SCL"; // PIN_WIRE_SCL = 7
    else if (pinIndex >= 2 && pinIndex < 32) {
      return "D" + (pinIndex);
    }
    return null;
  }

  private static String getRaspberryPiPicoPinLabel(int pinIndex) {
    if (pinIndex == 4) return "SDA"; // PIN_WIRE_SDA = 4
    else if (pinIndex == 5) return "SCL"; // PIN_WIRE_SCL = 5
    else if (pinIndex == 18) return "SPI0 SCK"; // PIN_SPI_SCK = 18
    else if (pinIndex == 19) return "SPI0 MOSI"; // PIN_SPI_MOSI = 19
    else if (pinIndex == 16) return "SPI0 MISO"; // PIN_SPI_MISO = 16
    else if (pinIndex == 17) return "SPI0 SS";   // PIN_SPI_SS  = 17
    else if (pinIndex == 0) return "UART0 TX";    // UART0 TX
    else if (pinIndex == 1) return "UART0 RX";    // UART0 RX
    else if (((pinIndex >= 0 && pinIndex < 23) || (pinIndex) == 25)) { // LED_BUILTIN is 25
      return "GPIO" + pinIndex;
    } else if (pinIndex >= 26 && pinIndex < 30) {
      return "A" + (pinIndex - 26); // A0-A3
    }
    return null;
  }

  private static String getUnoR4PinLabel(int pinIndex) {
    return getUnoPinLabel(pinIndex); // Pinout is same as classic UNO
  }

  public static Icon pinNameToIcon(String pinLabel) {
    if (pinLabel.startsWith("A")) {
      // Analog pin - Example: Orange/Yellow color, maybe a waveform icon
      return new Icon("fas fa-wave-square", "#FFA500"); // Orange - Example, choose a better icon name
    } else if (pinLabel.startsWith("SDA") || pinLabel.startsWith("SCL")) {
      // I2C pins (SDA, SCL) - Example: Purple color, maybe an I2C specific icon or communication icon
      return new Icon("fas fa-link", "#800080"); // Purple - Example, choose a better icon name, "fa-link" for connection
    } else if (pinLabel.startsWith("D")) {
      // Digital pin - Example: Blue/Green color, default pin icon or digital signal icon
      return new Icon("fas fa-digital-tachograph", "#177096"); // Blue - Example, "fa-digital-tachograph" - could represent digital signal
    } else if (pinLabel.startsWith("SPI")) { // Added for SPI labels like "SPI0 SCK", "SPI MOSI" etc.
      // SPI pins - Example: Red color, maybe a chip or SPI specific icon
      return new Icon("fas fa-microchip", "#FF0000"); // Red - Example, "fa-microchip" for SPI related
    } else if (pinLabel.startsWith("UART") || pinLabel.startsWith("Serial")) { // Added for UART/Serial labels
      // UART/Serial pins - Example: Teal color, maybe a serial port or communication icon
      return new Icon("fas fa-tty", "#008080"); // Teal - Example, "fa-tty" for teletype, representing serial communication
    }

    // Default icon for unknown or other pin types
    return new Icon("fas fa-map-pin", "#808080"); // Gray - Default, "fa-map-pin" - generic pin
  }

  public static String getPinLabel(String boardType, byte index) {
    String pinLabel = getPinLabelInternal(boardType, index);
    if (pinLabel == null) {
      return "Pin" + index;
    }
    return pinLabel;
  }

  public static int getPinOrder(String pinLabel) {
    pinLabel = pinLabel.split(" ")[0];
    try {
      if (pinLabel.startsWith("Pin")) {
        return Integer.parseInt(pinLabel.substring(3));
      } else if (pinLabel.startsWith("D")) {
        return Integer.parseInt(pinLabel.substring(1));
      } else if (pinLabel.startsWith("A")) {
        return 100 + Integer.parseInt(pinLabel.substring(1));
      } else if (pinLabel.equals("SDA")) {
        return 200;
      } else if (pinLabel.equals("SCL")) {
        return 201;
      } else if (pinLabel.equals("RX")) {
        return 250;
      } else if (pinLabel.equals("TX")) {
        return 251;
      }
    } catch (Exception ignore) {
    }
    return 1000;
  }
}
